### PR TITLE
Touch support for split view

### PR DESCRIPTION
**Pull request by FossPrime**
Adds touch support for split view resizing

### CODE REVIEW

**Comment by FossPrime** [comment]
[Screen recording 2023-06-10 18.36.45.webm](https://github.com/mathuo/dockview/assets/876076/d962300e-69b1-4cc8-b83c-dc26983d66d3)

**Comment by FossPrime** [comment]
Related Issue:
https://github.com/kat-tax/vslite/pull/18

**Comment by mathuo** [comment]
Thank you for the PR. I agree splitview resizers should support touch events and it shouldn't be a large change either. I will need to review and test it though before merging anything, including some unit tests.

Just a few things to note that we'll need to have to merge:
- a seperation between touch and mouse events
- unit tests
- for consistancy rather than returning a boolean from an event we can use event.preventDefault() which has the same affect and is the approach used elsewhere in the dockview codebase.

I did take a brief look at this on an alternative branch and came up with [this](https://github.com/mathuo/dockview/commit/003ebab544a7eb41760db4cbb268c3a502d27e17) but I do need to check it properly, happy to accept an adjusted PR otherwise I will get around to it within the next week hopefully.

**Comment by mathuo** [comment]
Moved changes into PR https://github.com/mathuo/dockview/pull/280 with preserved author so your contribution is still kept.

**Pull request closed without merging**
