### PR TITLE
chore: create new packages for supported frameworks

### PR DESCRIPTION
**Pull request by mathuo**

### CODE REVIEW

**Comment by eclipse313** [comment]
Thank you so much for creating this pull request and responding to my "issue"! I'm really excited about the project and it would be wonderful if I could replace my GoldenLayout project and switch to this.

The new structure will definitely make it easier for me and other developers to work on a Vue version (or versions for other frameworks). As soon as I get deep enough into the project, I would definitely try to participate and contribute source code.

Having a layout manager of the quality of dockview for our Vue project would be very important at the moment. It would be great if you could contact me at info@server-start.de so that we can discuss how we can drive the development forward (and perhaps also provide a little financial support).

Thanks!
Thomas

**Comment by jcuenod** [comment]
I would love to see a version for Solid-js!

**Comment by BlueBazze** [comment]
@eclipse313 This probably has your interest.

Got a basic vue version working.
Theres a bunch of stuff that does not work yet.

I did not use portals, just straight up rendered the components which seems to work.

There are some kinks that i havent figured out.
It seems that the props for panel, header and watermark components cannot access the api title and so on without updating, update another ref, basically the props are not reactive and i have no idea how to make them reactive..

I will not be actively maintaining a vue port, but i can help get it up and running.
At the moment i just did everything inside of a vue project, ill extract it tomorrow.


image

**Comment by eclipse313** [comment]
That sounds very interesting, thank you for your work! Once you've pushed it, I'll have a look to see if I can find the cause of the missing reactive. By "props for panel" do you mean that when I assign props to the component, they don't update?

**Comment by BlueBazze** [comment]
It is very cluttered. But there is a half working version up https://github.com/BlueBazze/dockview/tree/master/packages/dockview-vue

I used the default vue templates to create the package.
There is probably some configuration needed for vite to build the actual package.
So at the moment im guessing only the playground works.

**Comment by BlueBazze** [comment]
@mathuo Now that i think of it.. Would you rather have us make a pr based on master or this pr branch?

**Comment by mathuo** [comment]
> @mathuo Now that i think of it.. Would you rather have us make a pr based on master or this pr branch?

This branch is a little experimental. If you have a working example for Vue then I'm happy to accept that as a PR from your own branch.

I'm currently in the process of preparing [v1.10.0](https://github.com/mathuo/dockview/issues/476) which has a few large features but after that is released I'm hoping to have some time to look into multiple framework support, specifically getting both a Vue and an Angular package created.

**Comment by mathuo** [comment]
@techbech @husayt @kyDenZ @artaommahe @eclipse313 @jcuenod @BlueBazze 

As of version `1.14.0` [dockview-vue](https://www.npmjs.com/package/dockview-vue) is offically supported. I am in the process of updating the docs @ [dockview.dev](https://dockview.dev) where there are also some examples and the framework can be toggled to show examples in Vue.

image

Also find the raw list of examples @ [dockview.dev/templates](https://dockview.dev/templates).

I will be closing this PR and any further discussions can be added [here](https://github.com/mathuo/dockview/issues/562).

**Comment by husayt** [comment]
This is great @mathuo. thank you.

**Comment by BlueBazze** [comment]
Great work!

**Pull request closed without merging**
