### PR TITLE
feat: add remainIfEmpty options to DockviewGroupPanel

### PR DESCRIPTION
**Pull request by KaivnD**
Make this removeEmptyGroup configurable via group model, with this pr, we can keep group remain when group has no children by set `group.remainIfEmpty = true`.

I'm not sure this new property will cause problem or not, can you do the review? @mathuo 

#402

### CODE REVIEW

**Comment by techbech** [comment]
I'm interested in trying this out. Could you possible add a [sandbox to the docs package](https://github.com/mathuo/dockview/tree/master/packages/docs/sandboxes) and add it to the [dockview docs page](https://github.com/mathuo/dockview/blob/master/packages/docs/docs/components/dockview.mdx)

**Comment by KaivnD** [comment]
ok, I'll do it.

**Comment by martinzima** [comment]
Can we restore this pull request, please? I need this functionality and I don't see any other ways how to achieve this behavior right now.

**Comment by mathuo** [comment]
The problem with this is it's a little flakey since as panels move around groups can be re-created and re-assigned internally without the end users knowledge (for example, floating groups and popout groups).

Obviously it's something that would be good to support though, my initial thoughts since dockview is very much event-based would be to expose an event such as below, would something like this work? Would you need such state persisted between layouts?

```
api.onPanelRemovedFromGroup(event => {
    const group  = event.group
    const panel = event.panel

    // if condition matches
    event.preventGroupFromClosing()
});
```

**Comment by martinzima** [comment]
@mathuo Yes, I think that would work nicely for my use case. Basically, I'm trying to always have the primary group open, similarly to what is described in the original issue: https://github.com/mathuo/dockview/issues/402.

Should I try to come up with a PR, or is that someting that you want to take on? :)

**Pull request closed without merging**
